### PR TITLE
Fixed issues with callbacks from background page

### LINKED ISSUE #2: Subscription
So we've managed to setup onesignal fine, however when people run my extension they need to manually disable then re-enable the extension for oneSignal to generate a Onesingal playerID. Once they've done that it works perfectly.

Just wondering why google chromes initial load wouldn't trigger a creation of subscription?

### PR DESCRIPTION
**Pull request by jkasten2**
* Fixed issue where `getIdsAvailable` callback would never fire if it was called before   
    the device was registered with a player_id on the background page
* Fixed params sent to `getIdsAvailable` callback if fired after a player create.
* Fixed `addListenerForNotificationOpened` callback firing on background page.
* Internal refactor to handle callbacks via a new __OSMessageHelper class.
* Resolves #2

### CODE REVIEW

File: OneSignal.js [hunk 1]
```diff
@@ -64,6 +64,83 @@ var OneSignal = {
     xhr.open(action, ONESIGNAL_HOST_URL + url);
     xhr.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
     xhr.send(JSON.stringify(inData));
+  }
+};
+
+var __OSMessageHelper = {
+  // Dictionary of callbacks by type
+  // Each element is an array that can have a list of callbacks.
+  callbackHash: {},
```
Comment (rgomezp) [inline OneSignal.js:73]: let's have a dictionary `portHash` so that we can store the respective object types in the appropriate dictionary

File: OneSignal.js [hunk 2]
```diff
@@ -64,6 +64,83 @@ var OneSignal = {
...
+          // Will throw if port is disconnected. Ignore this error.
+          // Port becomes disconnectd if a client page is closed.
+        }
+      }
+      else
+        callback(value);
+    });
+  },
+
+  isAPort: function(obj) {
```
Comment (rgomezp) [inline OneSignal.js]: lets get rid of this (not needed because of new `portHash` object

File: OneSignal.js (hunk 1 above)
Comment (jkasten2) [reply OneSignal.js:73]: Fixed

File: OneSignal.js (hunk 2 above)
Comment (jkasten2) [reply OneSignal.js]: Fixed

**Review by rgomezp — APPROVED** [review]
LGTM
